### ISSUE TITLE
Gets stuck trying to load.

### ISSUE THREAD

**Issue by Kyno64** [MartinKuschnik/FFXIV-Zodiac-Glass#8]
Tried running the program on Win 10 and it hangs.  Only way to stop it from trying to load is logging off of windows.  Tried run as admin and compatibility mode.

**Comment by MartinKuschnik** [comment]
What do you mean with hangs?
Does the game hangs or windows itself?

I also use win 10 and had not such an issue.

It may be helpful if you provide me the log file from: %AppData%\ZodiacGlass\logs

**Comment by Kyno64** [comment]
11/15/2015 11:05:09 AM [Info]:  MemoryMap updated.
11/15/2015 11:23:02 AM [Trace]: Creating overlay for process 6904.
11/15/2015 11:25:07 AM [Error]: Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: Access is denied
   at ZodiacGlass.App.CreateOverlay(Process process) in C:\Users\Kyno\Downloads\FFXIV-Zodiac-Glass-1.4.1511.15001\FFXIV-Zodiac-Glass-1.4.1511.15001\Zodiac Glass\App.xaml.cs:line 484
   at ZodiacGlass.App.<>c__DisplayClass28_0.<OnProcessStarted>b__0() in C:\Users\Kyno\Downloads\FFXIV-Zodiac-Glass-1.4.1511.15001\FFXIV-Zodiac-Glass-1.4.1511.15001\Zodiac Glass\App.xaml.cs:line 550
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
11/15/2015 11:25:07 AM [Error]: Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: Access is denied
   at ZodiacGlass.App.CreateOverlay(Process process) in C:\Users\Kyno\Downloads\FFXIV-Zodiac-Glass-1.4.1511.15001\FFXIV-Zodiac-Glass-1.4.1511.15001\Zodiac Glass\App.xaml.cs:line 484
   at ZodiacGlass.App.<>c__DisplayClass28_0.<OnProcessStarted>b__0() in C:\Users\Kyno\Downloads\FFXIV-Zodiac-Glass-1.4.1511.15001\FFXIV-Zodiac-Glass-1.4.1511.15001\Zodiac Glass\App.xaml.cs:line 550
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at ZodiacGlass.App.Main() in C:\Users\Kyno\Downloads\FFXIV-Zodiac-Glass-1.4.1511.15001\FFXIV-Zodiac-Glass-1.4.1511.15001\Zodiac Glass\obj\x86\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
11/15/2015 11:25:21 AM [Trace]: Creating overlay for process 6904.
11/15/2015 11:25:54 AM [Trace]: Creating overlay for process 6904.
11/15/2015 11:27:35 AM [Trace]: Creating overlay for process 6904.
11/15/2015 11:28:40 AM [Trace]: Creating overlay for process 6904.

**Comment by MartinKuschnik** [comment]
There is only an error because you did not started the program as Admin.

Is this error new? Did you uses the program once before today?

Please also describe the issue a bit more.

**Comment by Kyno64** [comment]
I run it as admin. When i try to open it all i get is the spinning blue wheel.  It is not showing in task manager and does nothing else.  I can not try to run it again as when my mouse is over the .exe the blue wheel still shows up.

**Comment by Kyno64** [comment]
I have used this program before but a prior release.

**Comment by Kyno64** [comment]
Your Prior release for patch 3.01 still works for me.

**Comment by MartinKuschnik** [comment]
Ok, that is strange.

I'm searching for the reason.

**Comment by MartinKuschnik** [comment]
Can yo execute [this](https://github.com/MartinKuschnik/FFXIV-Zodiac-Glass/releases/tag/v1.4.1511.15002-TRACE) trace version and post me the log?

This helps me to trace down the issue.

**Comment by Kyno64** [comment]
Ran it in Visual Studio worked fine.  Built the .exe and same problem.  No log created.

**Comment by MartinKuschnik** [comment]
Also if you switch do Release in Visual Studio?

**Comment by Kyno64** [comment]
in release x86 it says did not start as admin.  If i build it and run the exe it does nothing.

**Comment by MartinKuschnik** [comment]
There we have a first hint.

**Comment by Kyno64** [comment]
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities.Sync\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. 
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Users\Kyno\Downloads\FFXIV-Zodiac-Glass-1.4.1511.15002-TRACE\FFXIV-Zodiac-Glass-1.4.1511.15002-TRACE\Zodiac Glass\bin\x86\Release\Zodiac Glass.vshost.exe'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Cannot find or open the PDB file.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Cannot find or open the PDB file.
The thread 0xa38 has exited with code 0 (0x0).
The thread 0x5f4 has exited with code 0 (0x0).
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Users\Kyno\Downloads\FFXIV-Zodiac-Glass-1.4.1511.15002-TRACE\FFXIV-Zodiac-Glass-1.4.1511.15002-TRACE\Zodiac Glass\bin\x86\Release\Zodiac Glass.exe'. Symbols loaded.
The thread 0x23cc has exited with code 0 (0x0).
The thread 0x9b0 has exited with code 0 (0x0).
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Cannot find or open the PDB file.
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'Microsoft.GeneratedCode'. 
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'Microsoft.GeneratedCode'. 
11/15/2015 12:36:09 PM [Trace]: Creating overlay for process 7756.
'Zodiac Glass.vshost.exe' (CLR v4.0.30319: Zodiac Glass.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll'. Cannot find or open the PDB file.
Exception thrown: 'System.ComponentModel.Win32Exception' in System.dll
Exception thrown: 'System.ComponentModel.Win32Exception' in Zodiac Glass.exe

**Comment by MartinKuschnik** [comment]
Please start your Visual Studio in Admin mode.

The Win32Exception should be the reason.

**Comment by Kyno64** [comment]
Works fine when i build the solution but not when i try to build the exe

**Comment by MartinKuschnik** [comment]
Can you try to clear the following folder: %AppData%..\..\Local\ZodiacGlass

**Comment by Kyno64** [comment]
No folder

**Comment by MartinKuschnik** [comment]
It's hard to trace the issue.
Maybe it helps to talk.
Would you like to have a Skype call?

Just add me: martin-kuschnik

**Comment by Kyno64** [comment]
k sent you a message

**Comment by Kyno64** [comment]
Version 1.4.1507.15001 seems to work fine for 3.1

**Comment by MartinKuschnik** [comment]
The issue was caused by avast Free Antivirus.
